### ISSUE TITLE
Error when joining game

### ISSUE THREAD

**Issue by CrocodileCroco** [rollerozxa/mineclone-alpha#10]
When i create a world, i get this error when joining
`AsyncErr: Lua: Runtime error from mod 'mcla_player' in callback environment_Step(): ...st/games/mineclone-alpha/mods/PLAYER/mcl_player/init.lua:162: attempt to index a nil value
stack traceback:
	...st/games/mineclone-alpha/mods/PLAYER/mcl_player/init.lua:162: in function <...st/games/mineclone-alpha/mods/PLAYER/mcl_player/init.lua:139>
	/app/share/minetest/builtin/game/register.lua:431: in function </app/share/minetest/builtin/game/register.lua:417>`

(my Minetest version is 5.6.1)

**Comment by rollerozxa** [comment]
Mineclone Alpha is dead from a million crashes caused by forking off of the ill-fated Mineclonia. Let it rest.
